autodl_llama:
  model_name: "llama3"
  url: "http://region-9.autodl.pro:34952/v1/"

stable_diffusion:
  url: "http://127.0.0.1:7860"
  default_negative_prompt: "lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,artist name,multiple views"
  model_name: "animagineXLV31_v31.safetensors [e3c47aedb0]"
